// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJAgWUjBSpFjcQdPlbwSsg6gylV2q_IjQ',
    appId: '1:439771829260:web:847993e7621cbbcd81ca29',
    messagingSenderId: '439771829260',
    projectId: 'uygunuburda-81794',
    authDomain: 'uygunuburda-81794.firebaseapp.com',
    databaseURL: 'https://uygunuburda-81794-default-rtdb.firebaseio.com',
    storageBucket: 'uygunuburda-81794.appspot.com',
    measurementId: 'G-91TC07YE50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnc-rTq5t0QUYyRD38-DgBTCxLwN9R-tk',
    appId: '1:439771829260:android:608327c2c1fa98f381ca29',
    messagingSenderId: '439771829260',
    projectId: 'uygunuburda-81794',
    databaseURL: 'https://uygunuburda-81794-default-rtdb.firebaseio.com',
    storageBucket: 'uygunuburda-81794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLO0Vx5L56rwoxlYaajC2WLoF5PeGkC8',
    appId: '1:439771829260:ios:aa79455887dbb71181ca29',
    messagingSenderId: '439771829260',
    projectId: 'uygunuburda-81794',
    databaseURL: 'https://uygunuburda-81794-default-rtdb.firebaseio.com',
    storageBucket: 'uygunuburda-81794.appspot.com',
    iosClientId: '439771829260-jqhd58uogfc80su8r7g6gpookjda2r7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.uygunuburda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZLO0Vx5L56rwoxlYaajC2WLoF5PeGkC8',
    appId: '1:439771829260:ios:aa79455887dbb71181ca29',
    messagingSenderId: '439771829260',
    projectId: 'uygunuburda-81794',
    databaseURL: 'https://uygunuburda-81794-default-rtdb.firebaseio.com',
    storageBucket: 'uygunuburda-81794.appspot.com',
    iosClientId: '439771829260-jqhd58uogfc80su8r7g6gpookjda2r7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.uygunuburda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJAgWUjBSpFjcQdPlbwSsg6gylV2q_IjQ',
    appId: '1:439771829260:web:ec510b5856d0253381ca29',
    messagingSenderId: '439771829260',
    projectId: 'uygunuburda-81794',
    authDomain: 'uygunuburda-81794.firebaseapp.com',
    databaseURL: 'https://uygunuburda-81794-default-rtdb.firebaseio.com',
    storageBucket: 'uygunuburda-81794.appspot.com',
    measurementId: 'G-JQEJL4GPG1',
  );
}
