import 'package:uygunuburda/features/authentication/models/model/brand_model.dart';
import 'package:uygunuburda/features/authentication/models/model/product_models.dart';

class MockData {
  static final List<Product> products = [
    Product(
      id: '1',
      title: 'Çaykur Tiryaki Çayı 1000 G',
      price: 157.50,
      thumbnail: 'assets/images/products/03111315-b8d5d1-1650x1650.jpg',
      isFeatured: true,
      categoryid: '5',
      images: 'assets/images/products/03111315-b8d5d1-1650x1650.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '2',
      title: 'Bor Şeker Toz Şeker 2 Kg',
      price: 76.95,
      thumbnail: 'assets/images/products/03310009-b1633f-1650x1650.jpg',
      isFeatured: true,
      categoryid: '4',
      images: 'assets/images/products/03310009-b1633f-1650x1650.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '3',
      title: 'Migros Ultra Çamaşır Suyu Fresh 1000 Ml',
      price: 28.95,
      thumbnail: 'assets/images/products/30569626-0c337c-1650x1650.jpg',
      isFeatured: false,
      categoryid: '9',
      images: 'assets/images/products/30569626-0c337c-1650x1650.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '4',
      title: 'Product 4',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: true,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '5',
      title: 'Product 5',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: true,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '6',
      title: 'Product 6',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: false,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '7',
      title: 'Product 7',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: true,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '8',
      title: 'Product 8',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: true,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '9',
      title: 'Product 9',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: true,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '10',
      title: 'Product 10',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: true,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
    Product(
      id: '11',
      title: 'Product 11',
      price: 100.0,
      thumbnail: 'https://example.com/image1.jpg',
      isFeatured: true,
      categoryid: 'cat1',
      images: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
      brand: BrandModel(id: 'brand1', name: 'Brand 1', image: ''),
    ),
  ];
}
